### ISSUE TITLE
GUID is incorrect

### ISSUE THREAD

**Issue by jmstopper** [dcooney/instant-images#11]
WordPress 5.2.4
twentynineteen
Only instant images activated

When using instant images to add images to the wordpress media library, the guid in the wp_posts is incorrect.

Inserting an image results in a guid of 

https://granola.test/wp-content/uploads/2019/10w0_v-hgrjtg.jpg 

where it should be 

https://granola.test/wp-content/uploads/2019/10/w0_v-hgrjtg.jpg

Where 10 is the month of the year.

**Comment by dcooney** [comment]
@jmstopper this is not happening for me on multiple environments. Have you tried another site or host to see if you can replicate?
