### ISSUE TITLE
Add Instant Images to Featured Image selector

### ISSUE THREAD

**Issue by lauragobrightly** [dcooney/instant-images#12]
Feature Request: Enable Instant Images for Featured Image

Steps to Reproduce:

- Create blog post using Gutenberg
- Select "Featured Image"
- Popup does not display Instant Images as a resource

https://www.dropbox.com/s/bcp0mvxsffv7cw7/Screenshot%202019-11-01%2014.20.06.png?dl=0

Thank you!

**Comment by dcooney** [comment]
@lauragobrightly I have not been able to figure out how to reliably add a tab here.
to set a featured image use the Instant Images Gutenberg sidebar module.
![image](https://user-images.githubusercontent.com/428624/68336602-bfc5af00-00ac-11ea-874d-cc1ba7eb4e75.png)

**Comment by lauragobrightly** [comment]
Thank you @dcooney this works well for users with administrator access. I just found another bug where the Gutenberg block doesn't work for Editor/Author roles. I'll file a separate bug.
