### ISSUE TITLE
WP Media Integration

### ISSUE THREAD

**Issue by dovy** [dcooney/instant-images#13]
Seriously love the plugin, just hate it's location. Your only real competitor is StockPack, and they have a proprietary API. Their interface is no where what yours is, but the location is perfect, right in the WP Media modal. You really should just stick what you have in that model. It would make your plugin 200x more powerful.

Great work, really impressive!

-- Creator of ReduxFramework (WordPress framework)

**Comment by dovy** [comment]
P.S. Yes I know you just added sidebar support, but you really should take a look at how https://wordpress.org/plugins/stockpack/. If you do that, you don't have to keep doing custom integrations.  ;)

**Comment by dcooney** [comment]
Closing as this is complete :)
