### ISSUE TITLE
Error: Unable to download image to server, please check your server permissions

### ISSUE THREAD

**Issue by rahulnever2far** [dcooney/instant-images#2]
When I navigate to WordPress `Dashboard > Media > Instant Images` and click on an image to download it, it shows the downloading icon. After 1-2 seconds the download icon gets replaced by an error icon. On hover the tool-tip says `Unable to download image to server, please check your server permissions`.

Another thing I noticed is, after I installed the plugin a new directory called `instant-images` gets created at `wp-content/uploads/`. In that directory an image file with a random name is created for each download but my system is unable to open it.

**Environment details:**
- Windows 10 1709
- WAMP 3.1 (64 bit)
- PHP 7.1.9
- memory_limit = 512M
- post_max_size = 512M
- upload_max_filesize = 512M
- max_execution_time = 3600
- WordPress 4.9.1
- WordPress theme: Twenty Seventeen 1.4
- Instant Images 3.0

Please let me know if you need any other information in order to figure our the issue.

**Comment by dcooney** [comment]
@rahulnever2far I've responded on the WP forums.
https://wordpress.org/support/topic/downloaded-image-doesnt-get-added-to-the-media-library/

**Comment by rahulnever2far** [comment]
These are separate issues. This one occurs only my localhost and the other one occurs on my Staging Server (which is on the web but password protected). Please reopen this issue.

After posting this issue, I realized the GitHub repo is a bit lonely. I was not sure if you are active here. That's why I posted the other issue in WP forums.

**Comment by rahulnever2far** [comment]
Here's the difference between both issues:
**Localhost (this issue):** It doesn't download the image.
**Password protected server (WP forums issue):** It downloads and resizes the image. But fails to add it to the Media Library.

Get this plugin to work on a localhost is more important (at least to me) because it would save a lot of time whenever there is a need of some sample images.

**Comment by rahulnever2far** [comment]
Please reopen this issue

**Comment by dcooney** [comment]
@rahulnever2far  Why does this issue need to be re-opened?

If you are still having issues with your localhost environment please feel free help by contributing to the plugin.

You can run `npm install` then `webpack -w` to start making modifications locally.

**Comment by rahulnever2far** [comment]
Because you assumed that this issue was same the one I created at WP forums and closed it.

I have been already looking into this but please don't close this issue if it isn't resolved.
