### ISSUE TITLE
Thumbnails not showing

### ISSUE THREAD

**Issue by ruijt** [dcooney/instant-images#20]
Hi,

I'm using Instant Images in combination with WP media folder and with Amazon S3 synchronisation.
https://www.joomunited.com/wordpress-products/wp-media-folder
https://www.joomunited.com/wordpress-products/wp-media-folder/amazon-s3-integration-with-wordpress-media-library

When I add an image with Instant Images, I can use the image without problems but in the media library the thumbnails and previews won't show.
Is this something (a problem) for Instant Images or for WP Media Folder?

Thanks!

<img width="1552" alt="Screenshot 2021-12-13 at 11 11 02" src="https://user-images.githubusercontent.com/4620461/145794062-01dd4d7e-0822-4159-9595-ff9e55a7a3ac.png">
<img width="1552" alt="Screenshot 2021-12-13 at 11 17 15" src="https://user-images.githubusercontent.com/4620461/145794174-cc238ce2-cfb3-4898-a977-5f93b6655930.png">

**Comment by dcooney** [comment]
@ruijt I'm not sure where the issue would be with this. Is the image not being sent to S3?
