### ISSUE TITLE
Open for other sources?

### ISSUE THREAD

**Issue by cfoellmann** [dcooney/instant-images#3]
Did you ever plan on supporting other sources?

I love unsplash but there is sooo much more like https://github.com/neutraltone/awesome-stock-resources#cc0-license + https://github.com/heyalexej/awesome-images

**Comment by dcooney** [comment]
Yes, but obviously they would require some sort of open API.
If you could filter a list I can look at adding additional sources.

**Comment by nabhacosley** [comment]
How about sites that use WordPress -- e.g. if you could auth with a WordPress install and use the REST API to pull in media from another site?

We would find that super useful; I'd be happy to help.

**Comment by nabhacosley** [comment]
In case anyone else wants to try connecting to another WordPress site's media library, here are the major changes.

API.js (update this with your site address)
```
module.exports = {
	photo_api: 'https://.../wp-json/wp/v2/media/?_embed',
	search_api: 'https://.../wp-json/wp/v2/media/?_embed',
	app_id: '',
	posts_per_page: '&per_page=20'
}
```

In PhotoList.js I had to update the search query (it uses search= instead of query=) and changed <Photo key> to result.slug. I also removed the tabs entirely.

In Photo.js I just mapped the data appropriately:

      this.id = this.props.result.id;
      this.thumb = this.props.result.media_details.sizes.thumbnail.source_url;     
      this.img = this.props.result.media_details.sizes.medium.source_url;                                     
      this.full_size = this.props.result.media_details.sizes.full.source_url;
      this.author = this.props.result.author; // @todo Use embedded data
      this.img_title = ''; // `${instant_img_localize.photo_by} ${this.author}`;  // @todo When real data exists in results    
      this.filename = this.props.result.slug;
      this.alt = this.props.result.alt_text;
      this.caption = ''; //this.props.result.caption.rendered;
      this.user = ''; //this.props.result.author; // @todo Use embedded data someday for the photographer
      this.user_photo = ''; // @todo Use embedded data
      this.link = this.props.result.link;
      this.likes = 0; // this.props.result.likes;
      this.view_all = instant_img_localize.view_all;
      this.like_text = instant_img_localize.likes;
      this.inProgress = false;
      this.container = document.querySelector('.instant-img-container');  

You can see how improvements could be made on that. But anyway, it wasn't too hard to do.

**Comment by sergio-fm** [comment]
Thank you so much for your awesome plugin Instant Images. It's really useful!
I have some suggestions for further plugin development:
1) add the ability to hide images that have already been used in the blog from search results;
2) add the ability to set the default search keyword and orientation of images.
