### ISSUE TITLE
Could openverse also be included?

### ISSUE THREAD

**Issue by lorandbognar** [dcooney/instant-images#40]
It would be cool if also openverse would be included here, considering it is wordpress's own provider. Is it this in the roadmap?

**Comment by dcooney** [comment]
Yea, I have this working and will be out in an upcoming release. Likely in the new year

**Comment by ellegaarddk** [comment]
This would be absolutely fantastic!

**Comment by dcooney** [comment]
Just released support for Openverse in 5.1.0.
https://wordpress.org/plugins/instant-images/

🥳
