### ISSUE TITLE
"Add Media" doesn't reload after an image is downloaded

### ISSUE THREAD

**Issue by nabhacosley** [dcooney/instant-images#5]
I noticed that after downloading an image, I had to close and re-open the Add Media modal to pick up on the new addition. It would be nice if that was automatic.

This code is surely not the ideal way to do it, but it does refresh the Add Media and Create Gallery panels when they are clicked on. I couldn't figure out how to refresh content in a frame that isn't currently visible. 

I just added this to initialize() in index.js.

		// Refresh Add Media and Create Gallery panels when we switch to them
		jQuery( ".media-menu>.media-menu-item:lt(2)", parent.document ).off( "click.AnandaStock" ); // Prevent duplicates being added
		jQuery( ".media-menu>.media-menu-item:lt(2)", parent.document ).on( "click.AnandaStock", { wp: parent.window.wp },function( event ) {   
			let wp = event.data.wp;
			wp.media.frame.content.get().collection.props.set({ignore: (+ new Date())});
			wp.media.frame.content.get().options.selection.reset(); 
		});

This plugin is really well made, by the way. Thanks (a lot!) for open-sourcing it.

**Comment by dcooney** [comment]
@nabhacosley Which version of the plugin were you testing with? I'm pretty sure I added support for this a few versions ago.

**Comment by dcooney** [comment]
@nabhacosley I believe this works in 4.0. Closing for now.
