### ISSUE TITLE
Incompatible With Hard-Coded Calls to wp_editor()

### ISSUE THREAD

**Issue by scofennell** [dcooney/instant-images#7]
Hi, I really like your plugin, it works great!  However my use case is a bit different.  I am using wp_editor() on the front and I'd like to get your media button to appear.  I was able to achieve this by changing just a couple of lines of code ( admin_enqueue_scripts to wp_enqueue_scripts and removing an is_admin() ), but I'd prefer not to hack your plugin.

What are your thoughts on this?

**Comment by dcooney** [comment]
@scofennell This would be a nice addition. I don't have free time at the moment, but I'm open to pull requests If you can sort this out using filters.

**Comment by scofennell** [comment]
Thank you for the response!  I have since completed my own API integration.
