### ISSUE TITLE
Add Hooks and Filters to insert function

### ISSUE THREAD

**Issue by derweili** [dcooney/instant-images#9]
It would be great if there were some actions and filters within the import (resize) process.

Those hooks could be used by developers to add additional data to images or to do something after an images was imported from unspash.

**Comment by dcooney** [comment]
@derweili 2 years later I've finally got around to this. In Instant Images `5.3.6` I've added a hook that fires after image upload.

```
function my_instant_images_callback( $args ) {
	print_r( $args );
}
add_action( 'instant_images_after_upload', 'my_instant_images_callback', 10, 2 );
```
